### ISSUE TITLE
Create bot helper commands

### ISSUE THREAD

**Issue by chadchristensen** [corinajacobson/azure-chatbot#3]

**Comment by chadchristensen** [comment]
Create regex case statements to recognize commands such as 'help', 'back', 'human', and 'paste error code'

**Comment by benmier** [comment]
I know where and how to put this in my NodeChatBot class. We can work together on this.

**Comment by chadchristensen** [comment]
Help command functionality has been placed in the NodeChatBot class.  The "back" command is waiting on the database to be up and running before it can be completed.
